version: '3'

networks:
  laravel:


services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      - ./src/dockerTest/public:/var/www/html/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

    networks:
      - laravel


  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_ALLOW_EMPTY_PASSWORD: 0
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "4306:3306"
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - mysql
    networks:
      - laravel
    ports:
      - "333:80"
    links:
      - mysql:db


  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    tty: true
    volumes:
      - ./src/dockerTest:/var/www/html/
    ports:
      - "9000:9000"
    networks:
      - laravel
